spring.application.name=ms-administracion-archivos
server.port=8080

logging.level.software.amazon.awssdk=DEBUG
logging.level.io.awspring.cloud=DEBUG

efs.path=/app/efs
aws.s3.bucket=sgdemob

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
